[2025-02-13T06:36:27.684+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T06:36:27.727+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sec_data_pipeline.download_zip manual__2025-02-13T06:36:22.718839+00:00 [queued]>
[2025-02-13T06:36:27.745+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sec_data_pipeline.download_zip manual__2025-02-13T06:36:22.718839+00:00 [queued]>
[2025-02-13T06:36:27.746+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-13T06:36:27.778+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_zip> on 2025-02-13 06:36:22.718839+00:00
[2025-02-13T06:36:27.794+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=52) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T06:36:27.798+0000] {standard_task_runner.py:72} INFO - Started process 53 to run task
[2025-02-13T06:36:27.798+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sec_data_pipeline', 'download_zip', 'manual__2025-02-13T06:36:22.718839+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/webscrape.py', '--cfg-path', '/tmp/tmpvphaxnkz']
[2025-02-13T06:36:27.803+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask download_zip
[2025-02-13T06:36:27.925+0000] {task_command.py:467} INFO - Running <TaskInstance: sec_data_pipeline.download_zip manual__2025-02-13T06:36:22.718839+00:00 [running]> on host 8857fc08f6e4
[2025-02-13T06:36:28.159+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sec_data_pipeline' AIRFLOW_CTX_TASK_ID='download_zip' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T06:36:22.718839+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T06:36:22.718839+00:00'
[2025-02-13T06:36:28.172+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T06:36:28.242+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-02-13T06:36:28.993+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-13T06:36:29.497+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-13T06:36:29.681+0000] {logger.py:11} INFO - There is no [linux64] chromedriver "133.0.6943.98" for browser google-chrome "133.0.6943" in cache
[2025-02-13T06:36:29.682+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-13T06:36:29.968+0000] {logger.py:11} INFO - WebDriver version 133.0.6943.98 selected
[2025-02-13T06:36:29.975+0000] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/linux64/chromedriver-linux64.zip
[2025-02-13T06:36:29.976+0000] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/linux64/chromedriver-linux64.zip
[2025-02-13T06:36:30.097+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-02-13T06:36:30.744+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-02-13T06:36:31.211+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/133.0.6943.98]
[2025-02-13T06:36:31.796+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/webscrape.py", line 53, in download_with_selenium
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x5649c2f03bba <unknown>
#1 0x5649c29a1790 <unknown>
#2 0x5649c29dabc5 <unknown>
#3 0x5649c29d692f <unknown>
#4 0x5649c2a27369 <unknown>
#5 0x5649c2a26896 <unknown>
#6 0x5649c2a18823 <unknown>
#7 0x5649c29e4a88 <unknown>
#8 0x5649c29e5bf1 <unknown>
#9 0x5649c2ecd15b <unknown>
#10 0x5649c2ed10e2 <unknown>
#11 0x5649c2eba01c <unknown>
#12 0x5649c2ed1cd4 <unknown>
#13 0x5649c2e9e48f <unknown>
#14 0x5649c2ef24f8 <unknown>
#15 0x5649c2ef26c9 <unknown>
#16 0x5649c2f02a36 <unknown>
#17 0x7f06599111c4 <unknown>

[2025-02-13T06:36:31.845+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=sec_data_pipeline, task_id=download_zip, run_id=manual__2025-02-13T06:36:22.718839+00:00, execution_date=20250213T063622, start_date=20250213T063627, end_date=20250213T063631
[2025-02-13T06:36:32.001+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T06:36:32.002+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task download_zip (Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x5649c2f03bba <unknown>
#1 0x5649c29a1790 <unknown>
#2 0x5649c29dabc5 <unknown>
#3 0x5649c29d692f <unknown>
#4 0x5649c2a27369 <unknown>
#5 0x5649c2a26896 <unknown>
#6 0x5649c2a18823 <unknown>
#7 0x5649c29e4a88 <unknown>
#8 0x5649c29e5bf1 <unknown>
#9 0x5649c2ecd15b <unknown>
#10 0x5649c2ed10e2 <unknown>
#11 0x5649c2eba01c <unknown>
#12 0x5649c2ed1cd4 <unknown>
#13 0x5649c2e9e48f <unknown>
#14 0x5649c2ef24f8 <unknown>
#15 0x5649c2ef26c9 <unknown>
#16 0x5649c2f02a36 <unknown>
#17 0x7f06599111c4 <unknown>
; 53)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/webscrape.py", line 53, in download_with_selenium
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x5649c2f03bba <unknown>
#1 0x5649c29a1790 <unknown>
#2 0x5649c29dabc5 <unknown>
#3 0x5649c29d692f <unknown>
#4 0x5649c2a27369 <unknown>
#5 0x5649c2a26896 <unknown>
#6 0x5649c2a18823 <unknown>
#7 0x5649c29e4a88 <unknown>
#8 0x5649c29e5bf1 <unknown>
#9 0x5649c2ecd15b <unknown>
#10 0x5649c2ed10e2 <unknown>
#11 0x5649c2eba01c <unknown>
#12 0x5649c2ed1cd4 <unknown>
#13 0x5649c2e9e48f <unknown>
#14 0x5649c2ef24f8 <unknown>
#15 0x5649c2ef26c9 <unknown>
#16 0x5649c2f02a36 <unknown>
#17 0x7f06599111c4 <unknown>

[2025-02-13T06:36:32.031+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T06:36:32.071+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T06:36:32.099+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
