[2025-02-14T20:05:28.080+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T20:05:28.110+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-etl-dag.proceed_with_next_task scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14T20:05:28.129+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-etl-dag.proceed_with_next_task scheduled__2025-02-13T00:00:00+00:00 [queued]>
[2025-02-14T20:05:28.130+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T20:05:28.158+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): proceed_with_next_task> on 2025-02-13 00:00:00+00:00
[2025-02-14T20:05:28.169+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T20:05:28.176+0000] {standard_task_runner.py:72} INFO - Started process 132 to run task
[2025-02-14T20:05:28.176+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt-etl-dag', 'proceed_with_next_task', 'scheduled__2025-02-13T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/dbt-etl.py', '--cfg-path', '/tmp/tmpnxvt71_g']
[2025-02-14T20:05:28.182+0000] {standard_task_runner.py:105} INFO - Job 182: Subtask proceed_with_next_task
[2025-02-14T20:05:28.298+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt-etl-dag.proceed_with_next_task scheduled__2025-02-13T00:00:00+00:00 [running]> on host aff10611ebf2
[2025-02-14T20:05:28.422+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-etl-dag' AIRFLOW_CTX_TASK_ID='proceed_with_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-13T00:00:00+00:00'
[2025-02-14T20:05:28.425+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T20:05:28.445+0000] {logging_mixin.py:190} INFO - All required tables exist. Proceeding with the next task...
[2025-02-14T20:05:28.446+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T20:05:28.459+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T20:05:28.460+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt-etl-dag, task_id=proceed_with_next_task, run_id=scheduled__2025-02-13T00:00:00+00:00, execution_date=20250213T000000, start_date=20250214T200528, end_date=20250214T200528
[2025-02-14T20:05:28.514+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T20:05:28.550+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T20:05:28.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
