[2025-02-14T20:15:12.884+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T20:15:12.901+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-etl-dag.proceed_with_next_task manual__2025-02-14T20:15:04.778487+00:00 [queued]>
[2025-02-14T20:15:12.911+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-etl-dag.proceed_with_next_task manual__2025-02-14T20:15:04.778487+00:00 [queued]>
[2025-02-14T20:15:12.912+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T20:15:12.925+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): proceed_with_next_task> on 2025-02-14 20:15:04.778487+00:00
[2025-02-14T20:15:12.932+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T20:15:12.934+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-02-14T20:15:12.933+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt-etl-dag', 'proceed_with_next_task', 'manual__2025-02-14T20:15:04.778487+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/dbt-etl.py', '--cfg-path', '/tmp/tmp1to_4_n_']
[2025-02-14T20:15:12.936+0000] {standard_task_runner.py:105} INFO - Job 190: Subtask proceed_with_next_task
[2025-02-14T20:15:12.979+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt-etl-dag.proceed_with_next_task manual__2025-02-14T20:15:04.778487+00:00 [running]> on host aff10611ebf2
[2025-02-14T20:15:13.046+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-etl-dag' AIRFLOW_CTX_TASK_ID='proceed_with_next_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T20:15:04.778487+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T20:15:04.778487+00:00'
[2025-02-14T20:15:13.048+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T20:15:13.058+0000] {logging_mixin.py:190} INFO - All required tables exist. Proceeding with the next task...
[2025-02-14T20:15:13.059+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T20:15:13.068+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T20:15:13.069+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt-etl-dag, task_id=proceed_with_next_task, run_id=manual__2025-02-14T20:15:04.778487+00:00, execution_date=20250214T201504, start_date=20250214T201512, end_date=20250214T201513
[2025-02-14T20:15:13.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T20:15:13.133+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T20:15:13.137+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
