[2025-02-14T11:10:51.100+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T11:10:51.121+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_all_snowflake_tables.decide_next_step manual__2025-02-14T11:10:45.399861+00:00 [queued]>
[2025-02-14T11:10:51.131+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_all_snowflake_tables.decide_next_step manual__2025-02-14T11:10:45.399861+00:00 [queued]>
[2025-02-14T11:10:51.132+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T11:10:51.144+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): decide_next_step> on 2025-02-14 11:10:45.399861+00:00
[2025-02-14T11:10:51.151+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T11:10:51.152+0000] {standard_task_runner.py:72} INFO - Started process 127 to run task
[2025-02-14T11:10:51.152+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'check_all_snowflake_tables', 'decide_next_step', 'manual__2025-02-14T11:10:45.399861+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/snow.py', '--cfg-path', '/tmp/tmp9rqm9zrb']
[2025-02-14T11:10:51.155+0000] {standard_task_runner.py:105} INFO - Job 84: Subtask decide_next_step
[2025-02-14T11:10:51.197+0000] {task_command.py:467} INFO - Running <TaskInstance: check_all_snowflake_tables.decide_next_step manual__2025-02-14T11:10:45.399861+00:00 [running]> on host 94016f1f831c
[2025-02-14T11:10:51.267+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_all_snowflake_tables' AIRFLOW_CTX_TASK_ID='decide_next_step' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T11:10:45.399861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T11:10:45.399861+00:00'
[2025-02-14T11:10:51.269+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T11:10:51.281+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-14T11:10:51.290+0000] {logging_mixin.py:190} INFO - üîç Debug: Retrieved XCom records: [{'COUNT(*)': 4}]
[2025-02-14T11:10:51.290+0000] {logging_mixin.py:190} INFO - Warning: Unexpected XCom format. Proceeding with failure path.
[2025-02-14T11:10:51.291+0000] {python.py:240} INFO - Done. Returned value was: no_required_tables_found
[2025-02-14T11:10:51.291+0000] {branch.py:38} INFO - Branch into no_required_tables_found
[2025-02-14T11:10:51.292+0000] {skipmixin.py:233} INFO - Following branch ('no_required_tables_found',)
[2025-02-14T11:10:51.299+0000] {skipmixin.py:281} INFO - Skipping tasks [('proceed_with_next_task', -1)]
[2025-02-14T11:10:51.325+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T11:10:51.326+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=check_all_snowflake_tables, task_id=decide_next_step, run_id=manual__2025-02-14T11:10:45.399861+00:00, execution_date=20250214T111045, start_date=20250214T111051, end_date=20250214T111051
[2025-02-14T11:10:51.367+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T11:10:51.386+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T11:10:51.389+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
